title: Playground

options:
  preview: https://kirbycopilot.com

columns:
  - width: 2/3
    fields:
      infoApiKey:
        label: Getting Started
        type: info
        theme: positive
        text: |
          In order to play with the **Kirby Copilot**, please provide your [OpenAI API key](https://platform.openai.com/api-keys) in the field below. If you don't have an API key yet, you can sign up for the [OpenAI API](https://platform.openai.com). The key is required to make client-side requests to the OpenAI API.
      apiKey:
        label: OpenAI API Key
        type: apiKey
        help: |
          The key will be saved to the **session storage** of your browser. It will not be stored server-side or in any other way.
  - width: 1/3
    fields:
      infoDocumentation:
        label: 📚 Documentation
        type: info
        theme: empty
        text: |
          Head over to the [Kirby Copilot website](https://kirbycopilot.com) to learn more about the plugin and how to use it.

  - width: 1/1
    fields:
      headline01:
        type: headline
        label: Copilot for Blocks Fields
  - width: 2/3
    fields:
      content01:
        label: Blocks
        type: blocks
  - width: 1/3
    sections:
      copilot01:
        type: copilot
        field: content01

  - width: 1/1
    fields:
      headline06:
        type: headline
        label: Copilot for Writer Fields
  - width: 2/3
    fields:
      content06:
        label: Writer
        type: writer
  - width: 1/3
    sections:
      copilot06:
        type: copilot
        field: content06

  - width: 1/1
    fields:
      headline02:
        type: headline
        label: Copilot for Textarea Fields
  - width: 2/3
    fields:
      content02:
        label: Textarea
        type: textarea
        buttons: false
  - width: 1/3
    sections:
      copilot02:
        type: copilot
        field: content02
        systemPrompt: Provide responses in plain text.

  - width: 1/1
    fields:
      headline05:
        type: headline
        label: Include Fields as Context
  - width: 2/3
    fields:
      info05:
        label: Info
        type: info
        theme: passive
        text: |
          Context is key to a good user prompt. The content from other fields of the same model are available in the user prompt. Wrap the field name in curly braces to use it as a placeholder.

          This prompt uses the field `date` from the bottom of this page:
          ```
          What is the current date? (Hint, it is {date}!)
          ```
      content05:
        label: Blocks
        type: blocks
  - width: 1/3
    sections:
      copilot05:
        type: copilot
        field: content05
        userPrompt: |
          What is the current date?
          (Hint, it is {date}!)
        files: false

  - width: 1/1
    fields:
      headline03:
        type: headline
        label: Pre-defined User Prompt
  - width: 2/3
    fields:
      info03:
        label: Info
        type: info
        theme: passive
        text: |
          Add a pre-defined user prompt with the `userPrompt` property.
      content03:
        label: Blocks
        type: blocks
  - width: 1/3
    sections:
      copilot03:
        type: copilot
        field: content03
        userPrompt: Write a short story about the future of the world.

  - width: 1/1
    fields:
      headline04:
        type: headline
        label: Non-editable Pre-defined User Prompt
  - width: 2/3
    fields:
      info04:
        label: Info
        type: info
        theme: passive
        text: |
          With both the `editable` and the `files` property set to `false`, the user prompt is not editable and no context files can be added, respectively.
      content04:
        label: Blocks
        type: blocks
  - width: 1/3
    sections:
      copilot04:
        type: copilot
        field: content04
        userPrompt: Write a short story about the future of the world.
        editable: false
        files: false

  - width: 1/1
    fields:
      headlineContext:
        type: headline
        label: Context
  - width: 2/3
    fields:
      intro:
        label: Intro
        type: text
      infoContext:
        label: Info
        type: info
        theme: passive
        text: |
          Access the fields above in any user prompt by using the placeholders `{intro}` and `{date}`.
  - width: 1/3
    fields:
      date:
        label: Date
        type: date
